"""add currency to savings

Revision ID: 8ce03f30d5e4
Revises: 
Create Date: 2026-04-12 10:58:10.608308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce03f30d5e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings', sa.Column('currency', sa.Enum('CAD', 'USD', 'EUR', 'JPY', name='currency_type', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings', 'currency')
    # ### end Alembic commands ###
